#!/bin/bash
# Template: Joplin MCP Wrapper Script
# This file is used as a template by install.sh
# The actual configuration is generated in ~/.joplin-mcp/run_mcp.sh
#
# DO NOT EDIT THIS FILE DIRECTLY
# Run ./install.sh to configure properly

export JOPLIN_TOKEN="TOKEN_JOPLIN"
export JOPLIN_PORT="41184"

exec ~/.joplin-mcp/venv/bin/python ~/.joplin-mcp/server.py
